#!/usr/bin/env bash
# Configure localhost to resolve to 127.0.0.2 and facebook.com to 8.8.8.8
sudo sed -i 's/^127\.0\.0\.1\s*localhost$/127.0.0.2 localhost/' /etc/hosts
grep -q "facebook.com" /etc/hosts || echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts > /dev/null
